### ISSUE TITLE
Epic: Deployments view

### ISSUE THREAD

**Issue by sagerb** [posit-dev/publisher#1005]
**Ideas from UX Document:**

DEPLOYMENTS

- [x] When no deployments exist, display a welcome message to prompt them to start the new deployment flow
    - New deployment flow: Use Multi-step interface to:
    - Name the deployment
    - Select the credential to use
    - Generate configuration? (if none exist)
    - Generate requirements.txt? (if none exit)
    - Confirm deploy now
- [x] View/title operations:
  - [x] Refresh list
  - [x] New deployment
- [x] Deployments listed by name
  - [x] Mouse-over displays multi-line info that we’re now showing on deployment card
- View/item/context operations:
  - [x] Delete
  - [x] Deploy 
  - [x] View deployment file
- [x] File watching: Update list when underlying files change (so all related commands automatically update the view)

### Tasks
- [x] https://github.com/posit-dev/publisher/issues/1008
- [x] https://github.com/posit-dev/publisher/issues/1010
- [x] https://github.com/posit-dev/publisher/issues/1027
- [x] https://github.com/posit-dev/publisher/issues/1017
- [x] https://github.com/posit-dev/publisher/issues/1026

#####  If there are no deployments present
1. Prompt for name
2. Prompt for credential, if there are more than one
3. Prompt for config, if there are more than one

##### If there is more than one deployment
1. Prompt for which deployment
2. If there are multiple credentials that match, then prompt
3. If there are multiple configurations, then prompt

#### Publishing flow from item/context of a deployment

1. If there are multiple credentials which match, then prompt
2. If there are multiple configurations, then prompt

#####  Deployment progress will be shown in progress window similar to `progress-sample`.
