### ISSUE TITLE
Create `TreeItem` component for VSCode webviews

### ISSUE THREAD

**Issue by dotNomad** [posit-dev/publisher#1334]
Very closely tied to #1333 but can be done in parallel. 

---

The [VSCode Tree View](https://code.visualstudio.com/api/extension-guides/tree-view) and its individual items are a great visual that users expect in VSCode. However the [`vscode-webview-ui-toolkit`](https://github.com/microsoft/vscode-webview-ui-toolkit/tree/main) does not include an option for a TreeView Item component to use in webview views.

To accomplish the UI's we want inside of a webview we have to implement our own. 

### Example

![Image](https://github.com/posit-dev/publisher/assets/19917631/98dd260b-e6d8-4ed5-9f0a-ba9af0f01dd5)

### Task

Implement a `TreeItem` component that has:

- [x] Title
  - See `package.json` in the example above
- [x] Sub-text
  - See `extension/vscode` in the example above
- [x] Hoverable styling
- [x] Click action to support clicking on the item to trigger an action
- [x] An actions slot for buttons that trigger actions
- [x] Support for icons
- [x] Indent guidelines

Note that not all of the above need to be done in one PR.

This task does not cover nesting `TreeItem`s that is a follow-up once basic functionality works.

### Resources

GitLens also utilizes their [own Tree component](https://github.com/gitkraken/vscode-gitlens/tree/main/src/webviews/apps/shared/components/tree) which may be helpful to look at (it is under MIT license, but is not available as a module).
