### ISSUE TITLE
Move web project to web-old for new config UI and setup vue-router

### ISSUE THREAD

**Issue by dotNomad** [posit-dev/publisher#367]
In the new configuration world the UI is a lot different. In an effort to speed up delivery, but leave old code as reference-able we plan to move the old frontend code to a new directory and start from scratch bringing in bits as we need them.

Tooling configurations will need to be copied over to the new `web` directory:
- eslint
- tsconfig
- vite
- etc

To accomplish the new configuration UI we will need to introduce [vue-router](https://router.vuejs.org/) to do page navigation. This can be done at the same time since we need to move over configurations and required files already.

This task will have a follow-up to remove the old code.

```[tasklist]
### Tasks
- [x] Move the `web` directory to an `web-old` directory
- [x] Copy over tooling configurations
- [x] Copy over required files like src/App.vue
- [x] All just/web targets function
- [x] All CI/CD works with the web directory as expected
```
