### ISSUE TITLE
Create stubs for new config based frontend pages

### ISSUE THREAD

**Issue by dotNomad** [posit-dev/publisher#369]
There are a few pages in the new configuration UI that we will need. This task is just to create stubs to handle the navigation in vue-router and via URLs, not to add anything to them. This will allow us to more easily work on this pages in parallel.

```[tasklist]
### Tasks
- [x] Setup vue-router
- [x] Create the Project page component
- [x] Create the Deployment Destination page component
- [x] Deployment Destination page component accepts ID prop from URL
- [x] Create the Publish Progress page component
- [x] Create URL vue router routes for each
```
