### ISSUE TITLE
Show Deployment Destinations on Project page

### ISSUE THREAD

**Issue by dotNomad** [posit-dev/publisher#370]
The Project page needs to fetch the different Deployment Destinations available to publish to and display them to the user. They should be links that navigate the user to the Deployment Destination page for the one clicked.

![Image](https://github.com/rstudio/publishing-client/assets/19917631/9a090d2b-6a5a-4228-b6f2-1dde1250be7d)

This task does not include designing the cards or styling the list of destinations, only collecting them via the API, presenting them, and making them links.

```[tasklist]
### Tasks
- [x] Create API module methods and types for fetch Deployment Destinations
- [x] Fetch the Deployment Destinations via API
- [x] Display each Deployment Destination to the user un-styled
- [x] Link to the individual Deployment Destination pages
```
