### ISSUE TITLE
Create and style Deployment Destination card component

### ISSUE THREAD

**Issue by dotNomad** [posit-dev/publisher#371]
On the Project page we want to display the Deployment Destinations as clickable cards that navigate to the Deployment Destination pages. It will use the data we get back from the API to style the different parts we want to display - the URL, content ID, and last published date.

![Image](https://github.com/rstudio/publishing-client/assets/19917631/011d5e8e-729b-4eee-85f8-30644292e94d)

This task does not include adding the click-able drop down menu on the card. That can be a follow-up.

```[tasklist]
### Tasks
- [x] Create the Deployment Destination card component
- [x] Style hover, focus states
- [x] Handle page width reactivity and light/dark mode
- [x] Use the new component on the Project page
```
