### ISSUE TITLE
Create Credential selection component

### ISSUE THREAD

**Issue by dotNomad** [posit-dev/publisher#374]
The Deployment Destination page must have a way for a user to select a credential that they want to use prior to publishing.

The credential selection component should allow the user to see all of their valid credentials for this Deployment Destination and select one. It should default to a valid credential where possible. If there is not a valid credential an error should be shown to the user.

Use v-model to sync data back to the parent.

![Image](https://github.com/rstudio/publishing-client/assets/19917631/08402ff4-0904-4e7f-ac82-5b5ffd3ae568)

```[tasklist]
### Tasks
- [ ] Add API module methods and types for fetching Accounts
- [ ] Style a Credential select form input component
- [ ] Use API and send destination info to filter valid credentials
- [ ] Show an error if there are no valid credentials to select
```
