### ISSUE TITLE
Use Deployment Destination and Credential Selection to Publish

### ISSUE THREAD

**Issue by dotNomad** [posit-dev/publisher#375]
Once the Credential Selection component is complete (#374) we can use the selection and the context of which Deployment Destination page we are on to make a publish attempt using the API when the Publish button is hit.

This does not include making a selection for a config file - only the default config file will be used for the Alpha release so that can be hard-coded.

```[tasklist]
### Tasks
- [x] Add API module methods and types for publishing
- [x] Use Credential selection and Deployment Destination ID to publish
- [x] Disable Publish button until the Publish is complete
```
