### ISSUE TITLE
Show Deployment Destination on its own page

### ISSUE THREAD

**Issue by dotNomad** [posit-dev/publisher#376]
The Deployment Destination page needs to fetch its data for eventual use in the styled components: #373 and #377.

![Image](https://github.com/rstudio/publishing-client/assets/19917631/58219ada-9155-421e-9b21-19e145e042ae)

This task does not include designing the page or styling the data. It is only collecting the data via the API and presenting it. This also doesn't include fetching the configuration data, just having the selected configuration ready to be used in another API call. This doesn't include showing the Credential selector or the Publish button.

```[tasklist]
### Tasks
- [x] Create API module methods and types for fetching a Deployment Destination
- [x] Fetch the Deployment Destinations via API using the ID of the page
- [x] Display Deployment Destination data to the user un-styled
```
