### ISSUE TITLE
Add config section to Deployment Destination with key value pairs

### ISSUE THREAD

**Issue by dotNomad** [posit-dev/publisher#377]
The Deployment Destination page needs to communicate to the user what the Publish action will do. In the simplest case that is displaying the key value pairs of the currently selected config file.

For Alpha this will only be the default config, and will not include a button to view, edit, or choose a new config. The config can be fetched using the known data from the Deployment Record, but in Alpha since we are only using the default configuration this can be hard-coded for now.

![Image](https://github.com/rstudio/publishing-client/assets/19917631/1264013c-e095-4953-9446-df8cf198e028)

```[tasklist]
### Tasks
- [x] Create API module methods and types for fetching the config file
- [x] Fetch the Config data using the API
- [x] Display the Key Value pairs in a Config Section component
```
