### ISSUE TITLE
Create and style Configuration card component

### ISSUE THREAD

**Issue by dotNomad** [posit-dev/publisher#378]
Similar to the Project page listing Deployment Destinations (#370 and #371) Configurations need to have their own cards to display.

These should be similar in style to the Deployment Destination cards.

This task does not include making the card a link since configuration management is not on the docket for the Alpha.

```[tasklist]
### Tasks
- [x] Create the Configuration card component
- [x] Style hover, focus states for eventually making these links
- [x] Handle page reactivity and light/dark mode
- [x] Use the new component on the Project page
```
