### ISSUE TITLE
Show Configurations on Project page

### ISSUE THREAD

**Issue by dotNomad** [posit-dev/publisher#379]
The Project page needs to fetch the different Configurations available and display them to the user. Since the Alpha will only support the default configuration these do not need to be links, just a visual for the user to understand that this configuration is available in the Project.

This task does not include designing the cards or styling the list of configurations, only collecting them via the API, and presenting them.

```[tasklist]
### Tasks
- [x] Create API module methods and types for fetching Configurations
- [x] Fetch the Configurations via API
- [x] Display each Configuration to the user un-styled
```
