### ISSUE TITLE
Files API

### ISSUE THREAD

**Issue by tdstein** [posit-dev/publisher#39]
```[tasklist]
### Tasks
- [ ] #40 
- [ ] https://github.com/rstudio/publishing-client/issues/41
- [ ] https://github.com/rstudio/publishing-client/issues/42
- [ ] https://github.com/rstudio/publishing-client/issues/43
- [ ] https://github.com/rstudio/publishing-client/issues/44
- [ ] https://github.com/rstudio/publishing-client/issues/45
- [ ] https://github.com/rstudio/publishing-client/issues/46
```
